/// Flutter icons CustomOutbox
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomOutbox
///      fonts:
///       - asset: fonts/CustomOutbox.ttf
///
/// 
/// * MFG Labs, Copyright (C) 2012 by Daniel Bruce
///         Author:    MFG Labs
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.mfglabs.com/
///
import 'package:flutter/widgets.dart';

class CustomOutbox {
  CustomOutbox._();

  static const _kFontFam = 'CustomOutbox';

  static const IconData baseline_move_to_inbox_24px = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData linkedin = const IconData(0xf05c, fontFamily: _kFontFam);
}
